export const defaultRouteParams = {
    useBrowser: '0',
    waitUntil: 'networkidle2',
    encoding: 'utf-8',
    filterCategory: '',
    maxItems: 20,
    concurency: 5,
    item: 'item',
};

export const defaultRouteParamsRss = {
    item: 'item',
    title: 'channel > title, feed > title',
    language: 'language',
    description: 'description',
    link: 'link',
    itemTitle: 'title',
    itemLink: 'link',
    itemDescription: 'description',
    itemPubDate: 'pubDate',
    itemGuid: 'guid',
    itemId: 'id',
    itemImage: 'image',
    itemAuthor: 'author, dc:creator',
    itemCategory: 'category',
    itemEnclosure: 'enclosure',
    itemUpdated: 'updated',
    itemContent: 'article',
    itemTitleAttr: '',
    itemLinkAttr: '',
    itemDescriptionAttr: '',
    itemPubDateAttr: '',
    itemGuidAttr: '',
    itemIdAttr: '',
    itemAuthorAttr: '',
    itemCategoryAttr: '',
    itemDescAttr: '',
};

export const defaultRouteParamsHtml = {
    item: '',
    title: '',
    language: '',
    description: '',
    link: '',
    itemTitle: '',
    itemLink: '',
    itemDescription: '',
    itemPubDate: '',
    itemGuid: '',
    itemId: '',
    itemImage: '',
    itemAuthor: '',
    itemCategory: '',
    itemEnclosure: '',
    itemUpdated: '',
    itemContent: '',
    itemTitleAttr: '',
    itemLinkAttr: '',
    itemDescriptionAttr: '',
    itemPubDateAttr: '',
    itemGuidAttr: '',
    itemIdAttr: '',
    itemAuthorAttr: '',
    itemCategoryAttr: '',
    itemDescAttr: '',
};
